baseURL                = "https://avimehenwal.in/"     # Your domain name. Must end with "/"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "@avimehenwal"
theme                  = "cupper-hugo-theme"
googleAnalytics        = "UA-113741959-1"
disqusShortname        = "yourdiscussshortname"
enableGitInfo          = true                          # https://gohugo.io/variables/git/

[taxonomies]
  tag       = "tags"
  category  = "categories"
  series    = "series"
  # versions  = "versions"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description      = "My website, blog, personal dropbox and a Korb. Learning should be free and so is this website"
  homeMetaContent  = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer           = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat       = "Jan 2, 2006"
  codePenUser      = "avimehenwal"
  katex            = true
  socialshare      = true
  lazySearch       = true
  statPagesNum     = 50
  googleTagManager = "GTM-PD4QRLX"

[menu]
  [[menu.nav]]
    name = "Search"
    url = "https://cse.google.com/cse?cx=010181463350939928324:jbo_i9sqixm"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.nav]]
    name = "Deutsche"
    url = "/deutsche/"
    weight = 4
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 5
  [[menu.nav]]
    name = "Categories"
    url = "/categories/"
    weight = 6
  [[menu.nav]]
    name = "Series"
    url = "/series/"
    weight = 7
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 8
  [[menu.nav]]
    name = "Contact"
    url = "/contact/"
    weight = 9
  [[menu.nav]]
    name = "Notes"
    url = "/notes/"
    weight = 10
  [[menu.nav]]
    name = "Bullet journal"
    url = "/bujo/"
    weight = 11

# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/
[[params.social]]
    url = "https://github.com/avimehenwal"
    icon = "github"

[[params.social]]
    url = "https://twitter.com/avimehenwal"
    icon = "twitter"

[[params.social]]
    url = "https://www.quora.com/profile/Avi-Mehenwal"
    icon = "quora"

[[params.social]]
    url = "https://www.linkedin.com/in/avimehenwal/"
    icon = "linkedin"

# Algolia search #4
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

# _target="blank" to external links
[blackfriday]
hrefTargetBlank = true