baseURL                = "https://avimehenwal.in/"     # Your domain name. Must end with "/"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "Avi Mehenwal @avimehenwal"
theme                  = "cupper-hugo-theme"
googleAnalytics        = "UA-113741959-1"
disqusShortname        = "yourdiscussshortname"
enableGitInfo          = true

[taxonomies]
  tag       = "tags"
  category  = "categories"
  series    = "series"
  # versions  = "versions"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description      = "Personal website and blog of Avi Mehenwal - the self proclaimed Engineer"
  homeMetaContent  = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer           = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat       = "Jan 2, 2006"
  codePenUser      = "someUser"
  katex            = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.nav]]
    name = "Categories"
    url = "/categories/"
    weight = 5
  [[menu.nav]]
    name = "Series"
    url = "/series/"
    weight = 6
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 7
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 8