baseURL                = "https://avimehenwal.in/"     # Your domain name. Must end with "/"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "@avimehenwal"
theme                  = "cupper-hugo-theme"
googleAnalytics        = "UA-113741959-1"
disqusShortname        = "yourdiscussshortname"
enableGitInfo          = true

[taxonomies]
  tag       = "tags"
  category  = "categories"
  series    = "series"
  # versions  = "versions"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description      = "My website, bog, personal dropbox or trash Korb whatever you call it. Learning should be free and so is this website"
  homeMetaContent  = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer           = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat       = "Jan 2, 2006"
  codePenUser      = "avimehenwal"
  katex            = true
  socialshare      = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.nav]]
    name = "Categories"
    url = "/categories/"
    weight = 5
  [[menu.nav]]
    name = "Series"
    url = "/series/"
    weight = 6
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 8
  [[menu.nav]]
    name = "Contact"
    url = "/contact/"
    weight = 7
  [[menu.nav]]
    name = "Notes"
    url = "/notes/"
    weight = 9
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 10


# # Social icons appear in introduction and contact section. Add as many more as you like.
# # Find icon names here: http://fontawesome.io/cheatsheet/
# [[params.social]]
#     url = "https://github.com/avimehenwal"
#     icon = "github"

# [[params.social]]
#     url = "https://twitter.com/avimehenwal"
#     icon = "twitter"

# [[params.social]]
#     url = "https://www.quora.com/profile/Avi-Mehenwal"
#     icon = "quora"

# [[params.social]]
#     url = "https://www.linkedin.com/in/avimehenwal/"
#     icon = "linkedin"

[params.social]  # Set your social account here, if you don't have some accounts just comment them
    a-envelope = "mailto:your@email.com"
    b-stack-overflow ="https://stackoverflow.com/users/12345678/john-doe"
    c-twitter = "https://twitter.com/johndoe"
    d-facebook = "https://www.facebook.com/johndoe"
    e-github = "https://github.com/johndoe"
    f-youtube = "https://www.youtube.com/channel/12345678"
    g-linkedin = "https://www.linkedin.com/johndoe"
    h-google = "https://plus.google.com/12345678"
    i-github = "https://github.com/johndoe"
    j-weibo = "https://weibo.com"
    k-weixin = "http://localhost:1313"
    l-tumblr = "https://www.tumblr.com/blog/johndoe"
    m-instagram = "https://instagram.com/johndoe"
    n-gitlab = "https://gitlab.com/johndoe"
    o-pinterest = "https://www.pinterest.com/johndoe/"

[outputs]
    home = ["HTML", "RSS", "JSON"]