backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    filter:
      field: language
      value: en
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Avi Mehenwal}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}